### ISSUE TITLE
蘑菇丁

### ISSUE THREAD

**Issue by Rootless-cmd** [ToWeLong/go-mogu#3]
蘑菇丁打卡不可用了，望作者更新

**Comment by towelong** [comment]
> 蘑菇丁打卡不可用了，望作者更新

可以用吧，我前一个月还在用

**Comment by Rootless-cmd** [comment]
感谢大佬，大佬yyds






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ToWeLong/go-mogu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月27日(星期二) 晚上10:19
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [ToWeLong/go-mogu] 蘑菇丁 (#3)





  
蘑菇丁打卡不可用了，望作者更新
  
可以用吧，我前一个月还在用
