### ISSUE TITLE
求大佬更新一下

### ISSUE THREAD

**Issue by xiaoyuhz** [ToWeLong/go-mogu#4]
打卡不了了求大佬更新一下

**Comment by towelong** [comment]
> 打卡不了了求大佬更新一下

能否私发一下你的账号密码，我蘑菇钉的计划停止了已经，私发至我的邮箱towelong@qq.com

**Comment by Rootless-cmd** [comment]
> > 打卡不了了求大佬更新一下
> 
> 可以私发一下你的账号密码，我的蘑菇钉的计划停止了，私发至我的邮箱[towelong@qq.com](mailto:towelong@qq.com)

感谢大佬！

**Comment by xiaoyuhz** [comment]
> > 打卡不了了求大佬更新一下
> 
> 可以私发一下你的账号密码，我的蘑菇钉的计划停止了，私发至我的邮箱[towelong@qq.com](mailto:towelong@qq.com)

谢谢大佬更新一下

**Comment by towelong** [comment]
已更新：[README](https://github.com/ToWeLong/go-mogu#readme)
