### ISSUE TITLE
蘑菇丁接口更新

### ISSUE THREAD

**Issue by NothAmor** [ToWeLong/go-mogu#9]
蘑菇丁的接口似乎更新了，在登陆和打卡的时候多了一个t的请求参数，请问您知道如何算吗？
顺便求更新。。

**Comment by towelong** [comment]
> 蘑菇丁的接口似乎更新了，在登陆和打卡的时候多了一个t的请求参数，请问您知道如何算吗？ 顺便求更新。。

不知道哎  我好久没用了  现在也没有账号

**Comment by laradocs** [comment]
> 蘑菇丁的接口似乎更新了，在登陆和打卡的时候多了一个t的请求参数，请问您知道如何算吗？ 顺便求更新。。

我最近写了一个蘑菇丁SDK，我在想怎么让它使用的方便一点。

**Comment by towelong** [comment]
> > 蘑菇丁的接口似乎更新了，在登陆和打卡的时候多了一个t的请求参数，请问您知道如何算吗？ 顺便求更新。。
> 
> 我最近写了一个蘑菇丁SDK，我在想怎么让它使用的方便一点。

可以写个网页，批量代挂。不一定非得用action

**Comment by NothAmor** [comment]
> > > 蘑菇丁的接口似乎更新了，在登陆和打卡的时候多了一个t的请求参数，请问您知道如何算吗？ 顺便求更新。。
> > 
> > 
> > 我最近写了一个蘑菇丁SDK，我在想怎么让它使用的方便一点。
> 
> 可以写个网页，批量代挂。不一定非得用action

嗯，已经写出来了
https://github.com/NothAmor/MoGuDing-Web
麻烦大佬啦
